### ISSUE TITLE
Autoprefixer not working

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-frontend-boost#39]
During Jan.20th demo using `_custom.scss`.

Test case was
```css
a { border-radius: 5px; }
```

**Comment by vincentmorneau** [comment]
False alarm. Autoprefixer is working, test case was bad.
```css
:fullscreen a {
    display: flex
}
```

compiles fine to 

```css
:-webkit-full-screen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: flex
}
:-moz-full-screen a {
    display: flex
}
:-ms-fullscreen a {
    display: -ms-flexbox;
    display: flex
}
:fullscreen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex
}
```

Will update the readme
